INSERT INTO note (title, content, subject, created_at, file_name, file_type, file_path, file_size, updated_at) VALUES
                                                                                                                   ('Java Basics', 'Intro to Java', 'Java', 'java.pdf', 'application/pdf', '/files/java.pdf', 123456),
                                                                                                                   ('Python 101', 'Getting started with Python', 'Python', 'python.pdf', 'application/pdf', '/files/python.pdf', 234567),
                                                                                                                   ('Spring Boot Guide', 'Basics of Spring Boot', 'Java', 'springboot.pdf', 'application/pdf', '/files/springboot.pdf', 345678),
                                                                                                                   ('HTML Cheatsheet', 'Quick reference for HTML tags', 'Web', 'html.pdf', 'application/pdf', '/files/html.pdf', 456789),
                                                                                                                   ('CSS Flexbox', 'How to use Flexbox in CSS', 'Web', 'flexbox.pdf', 'application/pdf', '/files/flexbox.pdf', 567890),
                                                                                                                   ('REST APIs', 'Understanding RESTful APIs', 'Backend', 'restapi.pdf', 'application/pdf', '/files/restapi.pdf', 678901),
                                                                                                                   ('JavaScript DOM', 'DOM manipulation in JS', 'JavaScript', 'dom.pdf', 'application/pdf', '/files/dom.pdf', 789012),
                                                                                                                   ('MySQL Queries', 'Basics of SQL queries', 'Database', 'mysql.pdf', 'application/pdf', '/files/mysql.pdf', 890123),
                                                                                                                   ('React Components', 'Intro to React components', 'React', 'react.pdf', 'application/pdf', '/files/react.pdf', 901234),
                                                                                                                   ('Git Essentials', 'Git commands and workflows', 'Tools', 'git.pdf', 'application/pdf', '/files/git.pdf', 1012345);
